--Snowflake 
USE ROLE ACCOUNTADMIN;

--Create Databse 
CREATE DATABASE IF NOT EXISTS FOOD_DELIVERY;

-- Create Warehouse 
CREATE WAREHOUSE FOOD_DELIVERY_WH
  WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;


--Create Schemas
USE DATABASE FOOD_DELIVERY;

CREATE IF NOT EXISTS SCHEMA RAW;
CREATE IF NOT EXISTS SCHEMA STAGING;
CREATE IF NOT EXISTS SCHEMA SEEDS;
CREATE IF NOT EXISTS SCHEMA MARTS;

