
USE ROLE ACCOUNTADMIN;
USE DATABASE FOOD_DELIVERY;
USE SCHEMA RAW;

--CSV file format:
CREATE OR REPLACE FILE FORMAT FOOD_DELIVERY.RAW.CSV_FMT
  TYPE = 'CSV'
  COMPRESSION = 'AUTO'
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('', '\\N', 'NULL')
  TRIM_SPACE = FALSE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

--internal stage
CREATE OR REPLACE STAGE FOOD_DELIVERY.RAW.FOOD_DELIVERY_STAGE
  FILE_FORMAT = FOOD_DELIVERY.RAW.CSV_FMT;

